exclude: ["alexquintino.github.io.sublime-project", "alexquintino.github.io.sublime-workspace"]
permalink: /blog/:title
gems:
  - jekyll-sitemap
  - jekyll-coffeescript
url: "http://alexquintino.github.io"
